# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colossus Framework
email: your-email@domain.com
description: Framework desenvolvido para Secretaria de Municipal de Educação.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: colussus
github_username:  colussus

# Build settings
markdown: kramdown
permalink: /:title
